// Supabase 연결 정보
window.SUPABASE_URL = "https://anwazpyepeqkbcxhnjsr.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFud2F6cHllcGVxa2JjeGhuanNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxODkzMDUsImV4cCI6MjEwMDc2NTMwNX0.xKDnOSClTqz1ciiYek3XI7r2lDrPFElAUKvfaprKAa8";
